version: '3.4'

services:
  nhsd.gpitf.buyingcatalog:
    image: nhsd.gpitf.buyingcatalog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    environment:
      - ASPNETCORE_ENVIRONMENT
      - CACHE_HOST
      - OIDC_ISSUER_URL
      - OIDC_USERINFO_URL
      - OIDC_AUDIENCE
      - DATASTORE_CONNECTIONTYPE
      - DATASTORE_CONNECTIONSTRING
      - LOG_CONNECTIONSTRING
      - SHAREPOINT_BASEURL
      - SHAREPOINT_ORGANISATIONSRELATIVEURL
      - SHAREPOINT_CLIENT_ID
      - SHAREPOINT_CLIENT_SECRET
      - CRM_APIURI
      - CRM_ACCESSTOKENURI
      - CRM_CLIENTID
      - CRM_CLIENTSECRET
      - USE_CRM
